jobs:
- job: test
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - checkout: self
    fetchDepth: 1
  - bash: "echo \"branch = $BUILD_SOURCEBRANCHNAME\" && [ \"master\" = \"$BUILD_SOURCEBRANCHNAME\" ]"
